name: Integration Tests (Except DataStore & API)
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
    id-token: write
    contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main'}}

jobs:
  analytics-test:
    name: Analytics Integration Tests
    uses: ./.github/workflows/integ_test_analytics.yml
    secrets: inherit

  push-notifications-test:
    name: Push Notifications Integration Tests
    uses: ./.github/workflows/integ_test_push_notifications.yml
    secrets: inherit

  predictions-test:
    name: Predictions Integration Tests
    uses: ./.github/workflows/integ_test_predictions.yml
    secrets: inherit

  auth-test:
    name: Auth Integration Tests
    uses: ./.github/workflows/integ_test_auth.yml
    secrets: inherit

  geo-test:
    name: Geo Integration Tests
    uses: ./.github/workflows/integ_test_geo.yml
    secrets: inherit

  storage-test:
    name: Storage Integration Tests
    uses: ./.github/workflows/integ_test_storage.yml
    secrets: inherit

  logging-test:
    name: Logging Integration Tests
    uses: ./.github/workflows/integ_test_logging.yml
    secrets: inherit
