name: IntegrationTest
on:
  push:
    branches: [pentest-main] # Will change to main

permissions:
    id-token: write
    contents: read 

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  prepare-for-test:
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Test if copying integrationtest resouces work
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: NA
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

  analytics-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: analytics
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Analytics/
          workspace: AnalyticsCategoryPlugin.xcworkspace
          scheme: AWSPinpointAnalyticsPluginIntegrationTests
          
  api-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: api
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/
          workspace: APICategoryPlugin.xcworkspace
          scheme: AWSAPICategoryPluginFunctionalTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/
          workspace: APICategoryPlugin.xcworkspace
          scheme: GraphQLWithIAMIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/
          workspace: APICategoryPlugin.xcworkspace
          scheme: GraphQLWithUserPoolIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/
          workspace: APICategoryPlugin.xcworkspace
          scheme: RESTWithIAMIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/
          workspace: APICategoryPlugin.xcworkspace
          scheme: RESTWithUserPoolIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/
          workspace: APICategoryPlugin.xcworkspace
          scheme: GraphQLWithLambdaAuthIntegrationTests

  auth-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: auth
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Auth/
          workspace: AWSCognitoAuthPlugin.xcworkspace
          scheme: AWSCognitoAuthPluginIntegrationTests

  datastore-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: datastore
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/DataStore/
          workspace: DataStoreCategoryPlugin.xcworkspace
          scheme: AWSDataStoreCategoryPluginIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/DataStore/
          workspace: DataStoreCategoryPlugin.xcworkspace
          scheme: AWSDataStoreCategoryPluginAuthIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/DataStore/
          workspace: DataStoreCategoryPlugin.xcworkspace
          scheme: AWSDataStoreCategoryPluginFlutterIntegrationTests

  geo-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: geo
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Geo/
          workspace: GeoCategoryPlugin.xcworkspace
          scheme: AWSLocationGeoPluginIntegrationTests
  
  predictions-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: predictions
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Predictions/
          workspace: PredictionsCategoryPlugin.xcworkspace
          scheme: AWSPredictionsPluginIntegrationTests

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Predictions/
          workspace: PredictionsCategoryPlugin.xcworkspace
          scheme: CoreMLPredictionsPluginIntegrationTests

  storage-integration-test:
    needs: prepare-for-test
    runs-on: macos-latest
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: storage
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Storage/
          workspace: StoragePlugin.xcworkspace
          scheme: AWSS3StoragePluginFunctionalTests
