name: Integration Tests | Predictions
on:
  workflow_dispatch:
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  predictions-integration-test-iOS:
    continue-on-error: true
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: predictions
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Predictions/Tests/PredictionsHostApp
          scheme: AWSPredictionsPluginIntegrationTests

  predictions-integration-test-tvOS:
    continue-on-error: true
    runs-on: macos-13
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: predictions
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Predictions/Tests/PredictionsHostApp
          scheme: AWSPredictionsPluginIntegrationTests
          destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=latest
          sdk: appletvsimulator
          xcode_path: '/Applications/Xcode_14.3.app'

  predictions-integration-test-watchOS:
    continue-on-error: true
    runs-on: macos-13
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy integration test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: predictions
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG }}

      - name: List the copied configurations
        run: ls ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Run Integration test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Predictions/Tests/PredictionsHostApp
          scheme: AWSPredictionsPluginIntegrationTestsWatch
          destination: platform=watchOS Simulator,name=Apple Watch Series 8 (45mm),OS=latest
          sdk: watchsimulator
          xcode_path: '/Applications/Xcode_14.3.app'
