name: Integration Tests
on:
  workflow_dispatch:
  workflow_call:

permissions:
    id-token: write
    contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-for-test:
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Verify copy resources
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: NA
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

  analytics-test:
    needs: prepare-for-test
    uses: ./.github/workflows/integ_test_analytics.yml
    secrets: inherit

  push-notifications-test:
    needs: prepare-for-test
    uses: ./.github/workflows/integ_test_push_notifications.yml
    secrets: inherit

  predictions-test:
    needs: prepare-for-test
    uses: ./.github/workflows/integ_test_predictions.yml
    secrets: inherit

  auth-test:
    needs: prepare-for-test
    uses: ./.github/workflows/integ_test_auth.yml
    secrets: inherit

  geo-test:
    needs: prepare-for-test
    uses: ./.github/workflows/integ_test_geo.yml
    secrets: inherit

  storage-test:
    needs: prepare-for-test
    uses: ./.github/workflows/integ_test_storage.yml
    secrets: inherit
