name: New Issue by Maintainer

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  maintainer-opened:
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && 
      contains(fromJSON('["palpatim", "5d", "harsh62", "thisisabhash", "ameter", "royjit", "atierian", "ukhan-amazon", "ruisebas", "phantumcode"]'), github.event.issue.user.login) ||
      contains(fromJSON('["drochetti", "mikepschneider", "lawmicha", "dcipoletti", "dpilch", "manueliglesias", "svidgen", "david-mcafee", "poojamat", "AaronZyLee", "marcvberg", "iartemiev", "phani-srikar", "sundersc", "alharris-at", "yeung-wah", "manaswi223"]'), github.event.issue.user.login)
    steps:
      - name: add message if maintainer opened
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment $ISSUE_NUMBER --repo aws-amplify/amplify-ios -b "This issue was opened by a maintainer of this repository; updates will be posted here. If you are also experiencing this issue, please comment here with any relevant information so that we're aware and can prioritize accordingly."
