name: Amplify Stress Tests
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
    id-token: write
    contents: read 

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-for-test:
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Verify copy resources
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: NA
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

  auth-stress-test:
    needs: prepare-for-test
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy stress test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: stresstest
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

      - name: Run stress test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Auth/Tests/AuthHostApp/
          scheme: AuthStressTests

  geo-stress-test:
    needs: prepare-for-test
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy stress test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: stresstest
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

      - name: Run stress test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Geo/Tests/GeoHostApp/
          scheme: GeoStressTests


  storage-stress-test:
    needs: prepare-for-test
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy stress test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: stresstest
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

      - name: Run stress test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/Storage/Tests/StorageHostApp/
          scheme: StorageStressTests
  
  datastore-stress-test:
    needs: prepare-for-test
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy stress test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: stresstest
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

      - name: Run stress test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/DataStore/Tests/DataStoreHostApp
          scheme: DatastoreStressTests

  grapql-api-stress-test:
    needs: prepare-for-test
    runs-on: macos-12
    environment: IntegrationTest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Make directory
        run: mkdir -p ~/.aws-amplify/amplify-ios/testconfiguration/

      - name: Copy stress test resouces
        uses: ./.github/composite_actions/download_test_configuration
        with:
          resource_subfolder: stresstest
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET_INTEG_V2 }}

      - name: Run stress test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          project_path: ./AmplifyPlugins/API/Tests/APIHostApp
          scheme: GraphQLAPIStressTests