name: Unit Tests | API
on:
  workflow_dispatch:
  workflow_call:

permissions:
    contents: read

jobs:
  api-unit-test-iOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
      - name: Run Unit Test Suite
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSAPIPlugin
          xcode_path: '/Applications/Xcode_14.3.app'

  api-unit-test-macOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
      - name: Run Unit Test Suite
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSAPIPlugin
          destination: platform=macOS,arch=x86_64
          sdk: macosx
          xcode_path: '/Applications/Xcode_14.3.app'

  api-unit-test-tvOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
      - name: Run Unit Test Suite
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSAPIPlugin
          destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=latest
          sdk: appletvsimulator
          xcode_path: '/Applications/Xcode_14.3.app'

  api-unit-test-watchOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
      - name: Run Unit Test Suite
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSAPIPlugin
          destination: platform=watchOS Simulator,name=Apple Watch Series 8 (45mm),OS=latest
          sdk: watchsimulator
          xcode_path: '/Applications/Xcode_14.3.app'
